import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "./lib/localfont";
import { ThemeProvider } from "next-themes";
import InternalLinkTooltip from "./component/internallink-tooltip";
import Header from "./component/header/header";
import { Suspense } from "react";
import Inspector from "./component/inspector/inspector";
import Script from "next/script";
import YoutubePlayer from "./component/music/YoutubePlayer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${pretendard.variable} antialiased font-normal md:overflow-hidden overflow-x-hidden bg-background`}
      >
        <Script
          src="//gc.zgo.at/count.js"
          data-goatcounter="https://solmiwiki.goatcounter.com/count"
          strategy="afterInteractive"
        />
        <ThemeProvider disableTransitionOnChange>
          <div className="flex h-screen w-full px-5 md:pt-5 gap-0 md:gap-7">

            <h1 className="hidden">page</h1>

            {/* 헤더 */}
            <Header />

            {/* 왼쪽 사이드 */}
            <Suspense>
              <Inspector />
            </Suspense>

            {/* 가운데 */}
            <main className="flex-1 flex flex-col  w-full pt-0 md:pt-5 md:w-[calc(100vw-26rem)] items-start overflow-hidden focus:outline-hidden">
              <div
                className='flex md:gap-4 w-full overflow-hidden focus:outline-hidden'
              >
                {children}
              </div>
            </main>
          </div>

          {/* 내부링크 툴팁 */}
          <InternalLinkTooltip />

          {/* 음악 */}
          <YoutubePlayer />
        </ThemeProvider>
      </body>
    </html>
  );
}
