// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "./lib/localfont";
import { ThemeProvider } from "next-themes";
import InternalLinkTooltip from "./component/internallink-tooltip";
import fs from 'fs';
import path from 'path';
import SideNav from "./component/side-nav";
import { Alert } from "./component/alert";
import Header from "./component/header";
import { gql, GraphQLClient } from "graphql-request";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new GraphQLClient(process.env.GRAPHQL_API_URL!);

const GET_ALL_POSTS = gql`
  query {
    posts {
      id
      title
      publishedAt
      meta
      excerpt
      thumbnail
      tags {
        name
      }
      keywords {
        name
      }
      content {
        document(hydrateRelationships: true)
      }
    }
  }
`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await client.request(GET_ALL_POSTS);
  const posts = data.posts;

  const tags = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'public/all-tags.json'), 'utf8'));
  const keywordsTag = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'public/top-keywords-tag.json'), 'utf8'));

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${pretendard.className} antialiased font-normal md:overflow-hidden`}
      >
        <ThemeProvider disableTransitionOnChange>
          <div className="flex flex-col md:flex-row h-screen w-full px-5 md:p-8 gap-4">
            <Suspense>
              <Header />
            </Suspense>
            <h1 className="hidden">page</h1>
            <SideNav posts={posts} tags={tags} kwByTag={keywordsTag} />
            <main className="relative left-0 top-0 md:absolute md:left-[24rem] flex flex-col h-full w-full md:w-[calc(100vw-26rem)] flex-1 items-start overflow-hidden focus:outline-hidden">
              {children}
            </main>
          </div>

          <InternalLinkTooltip />

          {/* <Alert /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}