import type { Metadata } from "next";
import "./globals.css";
import { maruburi, pretendard } from "./lib/localfont";
import { ThemeProvider } from "next-themes";
import InternalLinkTooltip from "./component/internallink-tooltip";
import fs from 'fs';
import path from 'path';
import Header from "./component/header/header";
import { Suspense } from "react";
import Inspector from "./component/inspector/inspector";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const postsPath = path.join(process.cwd(), "public/_all_posts.json");
  const posts = JSON.parse(fs.readFileSync(postsPath, "utf8"));

  const tags = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'public/all-tags.json'), 'utf8'));
  const keywordsTag = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'public/top-keywords-tag.json'), 'utf8'));

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${pretendard.variable} ${maruburi.className} antialiased font-normal md:overflow-hidden overflow-x-hidden`}
      >
        <Script
          src="//gc.zgo.at/count.js"
          data-goatcounter="https://solmiwiki.goatcounter.com/count"
          strategy="afterInteractive"
        />
        <ThemeProvider disableTransitionOnChange>
          <div className="flex h-screen w-full px-5 md:p-8 gap-0 md:gap-8">

            <h1 className="hidden">page</h1>

            {/* 헤더 */}
            <Header />

            {/* 왼쪽 사이드 */}
            <Suspense>
              <Inspector posts={posts} tags={tags} kwByTag={keywordsTag} />
            </Suspense>

            {/* 가운데 */}
            <main className="flex-1 flex flex-col h-full md:h-[calc(100vh-2rem)] w-full pt-0 md:pt-2 md:w-[calc(100vw-26rem)] items-start overflow-hidden focus:outline-hidden pb-5 md:pb-8">
              <div
                className='flex gap-8 w-full overflow-hidden focus:outline-hidden'
              >
                {children}
              </div>
            </main>
          </div>

          {/* 내부링크 툴팁 */}
          <InternalLinkTooltip />
        </ThemeProvider>
      </body>
    </html>
  );
}