import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "./lib/localfont";
import { ThemeProvider } from "next-themes";
import InternalLinkTooltip from "./component/internallink-tooltip";
import fs from 'fs';
import path from 'path';
import Header from "./component/header/header";
import { gql, GraphQLClient } from "graphql-request";
import { Suspense } from "react";
import Inspector from "./component/inspector/inspector";
import { Post } from "./lib/type";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new GraphQLClient(process.env.GRAPHQL_API_URL!);

const GET_ALL_POSTS = gql`
  query {
    posts {
      id
      title
      publishedAt
      meta
      excerpt
      thumbnail
      tags {
        name
      }
      keywords {
        name
      }
      content {
        document(hydrateRelationships: true)
      }
    }
  }
`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data:{posts: Post[]} = await client.request(GET_ALL_POSTS);
  const posts = data.posts;

  const tags = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'public/all-tags.json'), 'utf8'));
  const keywordsTag = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'public/top-keywords-tag.json'), 'utf8'));

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${pretendard.className} antialiased font-normal md:overflow-hidden`}
      >
        <ThemeProvider disableTransitionOnChange>
          <div className="flex h-screen w-full px-5 md:p-8 gap-0 md:gap-8">

            <h1 className="hidden">page</h1>

            {/* 헤더 */}
            <Suspense>
              <Header />
            </Suspense>

            {/* 왼쪽 사이드 */}
            <Suspense>
              <Inspector posts={posts} tags={tags} kwByTag={keywordsTag} />
            </Suspense>

            {/* 가운데 */}
            <main className="flex-1 flex flex-col h-[calc(100vh-2.5rem)] w-full mt-0 md:mt-2 md:w-[calc(100vw-26rem)] items-start overflow-hidden focus:outline-hidden pb-8">
              {children}
            </main>


          </div>

          {/* 내부링크 툴팁 */}
          <InternalLinkTooltip />
        </ThemeProvider>
      </body>
    </html>
  );
}